import type { Metadata } from "next";
import "./globals.css"; // Asegúrate de que esta importación incluya las fuentes necesarias
import "./fonts.css"; // Importa el archivo de fuentes personalizado
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sf-pro-display">
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
